import{CognitiveArchitecture}from'../core/architecture.js';import{scenarios}from'../demos/scenarios.js';
const scenarioSelect=document.querySelector('#scenarioSelect');const inputText=document.querySelector('#inputText');const stepButton=document.querySelector('#stepButton');const autoButton=document.querySelector('#autoButton');const resetButton=document.querySelector('#resetButton');const novelty=document.querySelector('#novelty');const constraint=document.querySelector('#constraint');const metacognition=document.querySelector('#metacognition');const cycleLabel=document.querySelector('#cycleLabel');const reflection=document.querySelector('#reflection');const nodeList=document.querySelector('#nodeList');const trace=document.querySelector('#trace');const topEdges=document.querySelector('#topEdges');const learnedEdges=document.querySelector('#learnedEdges');const candidateNodes=document.querySelector('#candidateNodes');
let architecture;let timer=null;
function boot(){scenarioSelect.innerHTML=scenarios.map((scenario,index)=>`<option value="${index}">${scenario.title}</option>`).join('');reset();bind();}
function bind(){stepButton.addEventListener('click',()=>step());autoButton.addEventListener('click',toggleAuto);resetButton.addEventListener('click',reset);scenarioSelect.addEventListener('change',reset);[novelty,constraint,metacognition].forEach((slider)=>slider.addEventListener('input',render));}
function reset(){stopAuto();architecture=new CognitiveArchitecture(scenarios[Number(scenarioSelect.value||0)]);inputText.value=architecture.scenario.prompt;render();}
function step(){architecture.step(inputText.value,{novelty:Number(novelty.value),constraint:Number(constraint.value),metacognition:Number(metacognition.value)});render();}
function toggleAuto(){if(timer){stopAuto();return;}autoButton.textContent='Pause';timer=setInterval(step,900);}
function stopAuto(){if(timer)clearInterval(timer);timer=null;if(autoButton)autoButton.textContent='Auto-run';}
function render(){const state=architecture.snapshot();cycleLabel.textContent=`Cycle ${state.cycle}`;reflection.textContent=state.lastReflection||'Ready to begin iterative updating.';renderNodes(state.nodes);renderThreads(state.threads);renderAssociations(state);}
function renderNodes(nodes){nodeList.innerHTML=nodes.map((node)=>`<article class="node-card"><div><strong>${node.label}</strong><span>${node.name}</span></div><meter min="0" max="1" value="${node.activation.toFixed(2)}"></meter><p>${node.description}</p></article>`).join('');}
function renderThreads(threads){trace.innerHTML=threads.length?threads.map((thread)=>`<article class="thread"><div><strong>Cycle ${thread.cycle}</strong><span>${Math.round(thread.integration*100)}% integrated</span></div><p>${thread.summary}</p></article>`).join(''):'<p class="empty">No cognitive thread has formed yet.</p>';}
function renderAssociations(state){topEdges.innerHTML=state.topEdges.length?state.topEdges.map(renderEdge).join(''):'<p class="empty">No edges yet.</p>';learnedEdges.innerHTML=state.lastStrengthened.length?state.lastStrengthened.slice(0,8).map(renderLearnedEdge).join(''):'<p class="empty">Run a cycle to see learning.</p>';candidateNodes.innerHTML=state.lastCandidates.length?state.lastCandidates.map(renderCandidate).join(''):'<p class="empty">Run a cycle to see candidate nodes.</p>';}
function renderEdge(edge){const classes=['edge-row'];if(edge.active)classes.push('active-edge');if(edge.primed)classes.push('primed-edge');return`<div class="${classes.join(' ')}"><span>${edge.a} <b>&lt;-&gt;</b> ${edge.b}</span><meter min="-1" max="1" value="${edge.weight.toFixed(2)}"></meter><em>${edge.weight.toFixed(2)}</em></div>`;}
function renderLearnedEdge(edge){return`<div class="edge-row learned-edge"><span>${edge.a} <b>&lt;-&gt;</b> ${edge.b}</span><em>+${edge.delta.toFixed(2)}</em></div>`;}
function renderCandidate(candidate){return`<div class="edge-row candidate-row"><span>${candidate.name}</span><meter min="0" max="1" value="${Math.min(candidate.score,1).toFixed(2)}"></meter><em>${candidate.score.toFixed(2)}</em></div>`;}
boot();
